name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # daily midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: meryambej
          outputs: ./dist/github-contribution-grid-snake.svg

      - name: Push SVG to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          directory: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
